### ISSUE TITLE
PDF import/embed

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#46]
"In my use case Importing a PDF file into a Page or Edgeless will be a great feature"

Source: https://community.affine.pro/c/feature-requests/import-export

**Comment by xell** [comment]
1. If "import" means "interpret the content of the PDF and convert them into rich-text or other editable blocks", then this function will not be considered in the near future because of its ultimately complexity.
2. Embedding the PDF as a customized block to display either a thumbnail or a real view might be considered in future milestone.
