### ISSUE TITLE
Importing a voice or audio

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE-Community#48]
Ability to import audio into AFFiNE, also open to direct recording.

Source: https://community.affine.pro/c/feature-requests/import-export

**Comment by xell** [comment]
As for the recording, it will not be considered in the near future because 1) almost every mainstream desktop and mobile OS offers audio recording function; 2) few users requested this.

As for the embedding of the video/audio content, see Joe's reply in https://github.com/toeverything/blocksuite/issues/3641
